-- 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 3마리의 이름과 보호 시작일을 조회
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
         LEFT JOIN ANIMAL_OUTS AS B
                   ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME
LIMIT 3