-- 코드를 작성해주세요
SELECT C.SUM_SCORE AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM  HR_EMPLOYEES B JOIN 
   ( SELECT SUM(SCORE) AS SUM_SCORE, EMP_NO FROM HR_GRADE GROUP BY EMP_NO) C 
   ON C.EMP_NO = B.EMP_NO
ORDER BY 1 DESC
LIMIT 1