
-- 평균을 직접 구했음 ; 
SELECT I.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,(ROUND(SM / CNT ,2)) AS SCORE
FROM REST_INFO AS I JOIN (
    SELECT REST_ID, MEMBER_ID, SUM(REVIEW_SCORE) AS SM , COUNT(REST_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC