SELECT I.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS, ROUND( AL/CNT,2) AS SCORE
FROM REST_INFO I JOIN (
    SELECT COUNT(REVIEW_ID) AS CNT, REST_ID,  SUM(REVIEW_SCORE) AS AL
    FROM REST_REVIEW 
    GROUP BY REST_ID
) R    
ON R.REST_ID = I.REST_ID 
WHERE ADDRESS LIKE "서울%"       --%서울%라고 해서 ㅠ
ORDER BY SCORE DESC, FAVORITES DESC