--Àçº¹½À ´çÃ·.. 

SELECT MONTH(C.START_DATE) AS MONTH ,CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
WHERE MONTH(START_DATE) IN (8,9,10) AND YEAR(START_DATE) = 2022 
AND CAR_ID IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID 
    HAVING COUNT(HISTORY_ID) > 4
)
GROUP BY MONTH, CAR_ID
HAVING RECORDS >=1
ORDER BY MONTH, CAR_ID DESC