SELECT N.APNT_NO ,N.PT_NAME, N.PT_NO, "CS" AS MCDP_CD, D.DR_NAME, N.APNT_YMD
FROM DOCTOR D JOIN
(
SELECT A.APNT_NO ,P.PT_NAME, A.PT_NO, A.MDDR_ID AS MD, APNT_YMD
FROM PATIENT P 
JOIN (SELECT PT_NO, MDDR_ID, APNT_YMD,APNT_NO
      FROM APPOINTMENT 
      WHERE MCDP_CD = "CS" 
      AND APNT_YMD LIKE "2022-04-13%"
      AND APNT_CNCL_YN = "N"
    ) A 
ON A.PT_NO = P.PT_NO  
) N
ON D.DR_ID =N.MD 
ORDER BY N.APNT_YMD