# 테이블 JOIN
# NULL 제거 (HAVING 으로도 가능)
# 그룹화, 정렬
# USER_ID 기준 중복 제거 (DISTINCT)
# 동일한 날짜, 회원 ID, 상품 ID 조합에 대해서는 하나의 판매 데이터만 존재합니다.
# 중복 제거를 놓쳤다.
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE AS O
         JOIN USER_INFO AS U
              ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER