WITH FRONTEND AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY LIKE "Front End"
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS A
         JOIN FRONTEND B
              ON A.SKILL_CODE & B.CODE
ORDER BY ID