-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A 
 JOIN FISH_NAME_INFO B
 ON A.FISH_TYPE = B.FISH_TYPE
WHERE LENGTH = (
  SELECT MAX(LENGTH)
  FROM FISH_INFO  
  GROUP BY FISH_TYPE
  HAVING FISH_TYPE = A.FISH_TYPE
)
ORDER BY 1