#SUM(PRICE*C.SALES) 이걸 SUM(SALES) * PRICE로 생각해서 틀렸다. ㅜㅜ

SELECT #B.BOOK_ID,  
B.AUTHOR_ID,AUTHOR_NAME,CATEGORY,
SUM(PRICE*C.SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES C 
ON B.BOOK_ID = C.BOOK_ID
JOIN AUTHOR A 
ON B.AUTHOR_ID = A.AUTHOR_ID

WHERE C.SALES_DATE LIKE "2022-01%"

GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC