-- MONTH(컬럼명) / YEAR() / DAYOFMONTH() 등으로 데이터 추출가능
SELECT DISTINCT(A.CAR_ID )
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A,CAR_RENTAL_COMPANY_CAR AS B
WHERE A.CAR_ID = B.CAR_ID AND CAR_TYPE = '세단' AND MONTH(START_DATE) = "10"
ORDER BY CAR_ID DESC