-- 코드를 입력하세요
SELECT concat('/home/grep/src/',A.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS A,USED_GOODS_BOARD AS B
WHERE A.BOARD_ID = B.BOARD_ID AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD )
ORDER BY FILE_ID DESC