-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- 처음에는 from에 서브쿼리를 줘서 하려고 했는데 쉽지 않았다. 
-- 앞으로는 서브쿼리 뿐만 아니라 where 컬럼 in ()도 생각해야겠다.

SELECT  MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID 
    HAVING COUNT(HISTORY_ID) > 4
) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
-- 여기서 한번더 AND 조건을 주는 이유는 8 9 10월이 아닌 CAR_ID는 NULL을 가지고 오기 때문
GROUP BY MONTH , CAR_ID
HAVING RECORDS >=1
ORDER BY MONTH , CAR_ID DESC