-- 코드를 입력하세요

WITH USERS AS(
    SELECT F.USER_ID 
    FROM USER_INFO F
    WHERE JOINED LIKE "2021-%")


SELECT "2022" AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(A.USER_ID)) AS PUCHASED_USERS,
ROUND( COUNT(DISTINCT(A.USER_ID)) / (SELECT COUNT(*) FROM USERS)  ,1) AS PUCHASED_RATIO
FROM (
    SELECT *
    FROM ONLINE_SALE O
    WHERE O.USER_ID IN (SELECT * FROM USERS)
) A
WHERE SALES_DATE LIKE "2022-%"
GROUP BY MONTH
ORDER BY MONTH


