# A -> B로 업그레이드 가능
# A = PARENT 아이템
# PARENT 없음 = ROOT 아이템
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO AS A
         LEFT OUTER JOIN ITEM_TREE AS B
                         ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.ITEM_ID IS NULL
ORDER BY ITEM_ID DESC