-- REGEXP_REPLACE(TLNO, '(.{3})(.{4})(.{4})', '$1-$2-$3') 
SELECT A.WRITER_ID, NICKNAME, CONCAT(CITY," ", STREET_ADDRESS1," ", STREET_ADDRESS2) AS 전체주소,
REGEXP_REPLACE(TLNO, '(02|.{3})(.+)(.{4})', '$1-$2-$3') AS 전화번호
FROM 
(
SELECT  WRITER_ID, COUNT(BOARD_ID) AS CNT
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
) A, USED_GOODS_USER B
WHERE CNT>=3 AND
        A.WRITER_ID = B.USER_ID
ORDER BY USER_ID DESC


