-- Having 절로 해보려다가 잘 안됐다..
-- 그리고 IN을 사용해야하는 지 몰랐다

SELECT FOOD_TYPE, REST_ID,REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (SELECT MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC