-- 
# SELECT PRODUCT_CODE,  SUM(PRICE*SALES_AMOUNT) AS SALES
# FROM PRODUCT as A, OFFLINE_SALE as B
# WHERE A.PRODUCT_ID = B.PRODUCT_ID
# GROUP BY B.PRODUCT_ID
# ORDER BY SALES DESC , PRODUCT_CODE ASC

-- 
SELECT PRODUCT_CODE,  SUM(PRICE*SALES_AMOUNT) AS SALES
FROM PRODUCT A 
JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID
ORDER BY SALES DESC , PRODUCT_CODE ASC