# 한 번에 맞았다. 기분 좋음 ㅎㅎ
SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE (CAR_TYPE, OPTIONS) IN (
    SELECT CAR_TYPE, OPTIONS
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE OPTIONS LIKE "%통풍시트%" OR
            OPTIONS LIKE "%열선시트%" OR
            OPTIONS LIKE "%가죽시트%")
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE