-- 일단 KM를 쓰면 정렬이 안된다!
-- 소수 셋째자리에서 반올림이였는데 셋째까지인줄 알았다 
SELECT A.ROUTE, CONCAT( A.DIST,"km") AS TOTAL_DISTANCE, 
CONCAT(A.AVG_DIST ,"km") AS AVERAGE_DISTANCE
FROM (
    SELECT ROUTE, ROUND(SUM(D_BETWEEN_DIST),1) AS DIST , 
    ROUND(AVG(D_BETWEEN_DIST),2 ) AS AVG_DIST
    FROM SUBWAY_DISTANCE 
    GROUP BY ROUTE
    ORDER BY DIST DESC
) A