-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D 
WHERE D.SKILL_CODE & 
(SELECT S.CODE FROM SKILLCODES S WHERE S.NAME = "Python")
OR D.SKILL_CODE & 
(SELECT S.CODE FROM SKILLCODES S WHERE S.NAME = "C#")
ORDER BY ID