-- 코드를 작성해주세요
SELECT
    CONCAT(CASE WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN 1
                WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN 2
                WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN 3
                ELSE 4
               END,'Q') AS QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER