SELECT B.PRODUCT_ID, A.PRODUCT_NAME, 
SUM(B.AMOUNT*A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
JOIN FOOD_ORDER AS B ON
A.PRODUCT_ID = B.PRODUCT_ID
WHERE DATE_FORMAT(B.PRODUCE_DATE,'%Y-%m') = '2022-05'
--WHERE MONTH(IN_DATE) = 05 AND YEAR(IN_DATE) = 2022 이거는 왜 안될까
GROUP BY B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC