-- 코드를 작성해주세요
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO A
WHERE A.FISH_TYPE = (SELECT B.FISH_TYPE FROM FISH_NAME_INFO B WHERE FISH_NAME = "BASS") 
OR A.FISH_TYPE = (SELECT B.FISH_TYPE FROM FISH_NAME_INFO B WHERE FISH_NAME = "SNAPPER") 