# WITH 문을 처음 사용해 봄
# 너무 어려웠다 ..
#TIMESTAMPDIFF => 날짜 차이 계산해주는 함수
# COALESCE(DISCOUNT_RATE,0) DISCOUNT_RATE가 NULL이면 0으로 바뀜
#LEFT JOIN 은 왼쪽 테이블에 해당하는 합집합


WITH RENTAL_DAYS AS (
    SELECT * , TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1 AS RENTAL_DATE  
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    USING(CAR_ID)
), EXTRACT_DATE_TYPE AS(
    SELECT *,
    CASE
    WHEN RENTAL_DATE < 7 THEN NULL
    WHEN RENTAL_DATE < 30 THEN '7일 이상'
    WHEN RENTAL_DATE < 90 THEN '30일 이상'
    ELSE '90일 이상'
    END AS DUR_TYPE
    FROM RENTAL_DAYS
), EXTRACT_DISCOUNT_RATE AS (
    SELECT E.CAR_TYPE, HISTORY_ID, RENTAL_DATE, DAILY_FEE, COALESCE(DISCOUNT_RATE,0) AS DISCOUNT_RATE
    FROM EXTRACT_DATE_TYPE E LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON E.CAR_TYPE = P.CAR_TYPE AND DUR_TYPE = DURATION_TYPE
    WHERE E.CAR_TYPE ='트럭'
    GROUP BY HISTORY_ID
)

SELECT HISTORY_ID, FLOOR( RENTAL_DATE * DAILY_FEE *(1-DISCOUNT_RATE/100) ) AS FEE
FROM EXTRACT_DISCOUNT_RATE
ORDER BY FEE DESC, HISTORY_ID DESC