SELECT A.N AS HOUR , IFNULL(B.CNT,0) AS CNT
FROM (
SELECT @N := @N +1 AS N
FROM ANIMAL_OUTS, (SELECT @N:=-1 FROM DUAL) NN
LIMIT 24) A
LEFT JOIN
(
SELECT HOUR(DATETIME)AS HOUR, COUNT (ANIMAL_ID) AS CNT
FROM ANIMAL_OUTS 
GROUP BY HOUR
)B
ON A.N = B.HOUR