-- 코드를 입력하세요
SELECT B.ID , B.NAME, B.HOST_ID
FROM ( 
      SELECT ID, HOST_ID ,NAME
      FROM PLACES
      GROUP BY HOST_ID
      HAVING COUNT(ID) >1
) A , PLACES B
WHERE A.HOST_ID = B.HOST_ID
ORDER BY 1
