-- DISTINCT ¶û IS NOT NULL ÀÌ¶û JOIN .. 
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(B.USER_ID)) AS USERS
FROM USER_INFO AS A JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER