-- 코드를 입력하세요
WITH SORT_P AS (
    SELECT TRUNCATE(PRICE/10000,0) AS "PR", PRODUCT_ID
    FROM PRODUCT
)

SELECT (PR*10000) AS PRICE_GROUP , COUNT( PRODUCT_ID) AS PRODUCTS
FROM SORT_P
GROUP BY SORT_P.PR
ORDER BY 1


