# 처음에는 10월 조건을 LIKE 로 걸었는데, 정답이긴 함
# MONTH 로 하는 게 좋을 거 같다
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE C.CAR_ID = H.CAR_ID AND
        C.CAR_TYPE = "세단" AND
        H.START_DATE LIKE "%-10-%"
ORDER BY C.CAR_ID DESC

SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE C.CAR_ID = H.CAR_ID AND
        C.CAR_TYPE = "세단" AND
        MONTH(H.START_DATE) = 10
ORDER BY C.CAR_ID DESC