-- B.FISH_TYPE으로 그룹바이 하면 오류 NAME으로 묶으니까 정답

SELECT COUNT(B.ID) AS FISH_COUNT , C.FISH_NAME
FROM (SELECT ID, FISH_TYPE
      FROM FISH_INFO 
     ) B JOIN FISH_NAME_INFO C ON B.FISH_TYPE = C.FISH_TYPE
GROUP BY C.FISH_NAME
ORDER BY 1 DESC