SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM (SELECT COUNT(B.MEMBER_ID) AS ID_CNT, MEMBER_ID
                           FROM REST_REVIEW AS B 
                           GROUP BY MEMBER_ID
) AS C
JOIN MEMBER_PROFILE AS A ON A.MEMBER_ID = C.MEMBER_ID 
JOIN REST_REVIEW AS RV ON RV.MEMBER_ID = C.MEMBER_ID 
AND ID_CNT IN (SELECT MAX(ID_CNT)
                 FROM ( SELECT COUNT(MEMBER_ID) AS ID_CNT
                           FROM REST_REVIEW 
                           GROUP BY MEMBER_ID
) AS D
                 )
ORDER BY 3,2