
SELECT I.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,R_A.SCORE
FROM REST_INFO AS I JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE 
    FROM REST_REVIEW 
    GROUP BY REST_ID ) AS R_A
ON I.REST_ID = R_A.REST_ID
WHERE I.ADDRESS LIKE '¼­¿ï%'
ORDER BY R_A.SCORE DESC, FAVORITES DESC
