-- 코드를 작성해주세요
SELECT A.DEPT_ID , A.DEPT_NAME_EN, RR AS AVG_SAL
FROM HR_DEPARTMENT A 
JOIN
(   SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS RR
    FROM HR_EMPLOYEES 
    GROUP BY 1) B 
ON A.DEPT_ID = B.DEPT_ID
ORDER BY AVG_SAL DESC
