# 조인을 쓰고 싶어서 도전해보다가 서브쿼리가 더 쉽겠다는 생각함  
# 저렇게 테이블도 서브쿼리가 된다는 것을 앎
SELECT A.FLAVOR
FROM FIRST_HALF AS A , (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_T
    FROM JULY GROUP BY FLAVOR) AS B
WHERE A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.JULY_T) DESC
LIMIT 3