-- 코드를 작성해주세요
-- NTILE SQLD 때 알았는데 막상 문제로 보니 떠오르지 않았다 ㅠㅡㅠ
SELECT
    A.ID,
    CASE
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 4 THEN 'LOW'
        END AS COLONY_NAME
FROM ECOLI_DATA AS A
ORDER BY A.ID;