-- CONV() 를 사용해서 나누거나 포함으로 판단하려고 했지만 실패
-- WITH 문을 써야한다
-- CODE의 값은 2의 거듭제곱 꼴이므로 비트연산으로 구할 수 있다.
-- 16 + 2048 =  2064 / 16 | 2048 = 2064

WITH FRONT AS (
    SELECT BIT_OR(CODE) AS SKILL_CODE
    FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY ="Front End"
),
GRADE_TABLE AS (
    SELECT
    CASE WHEN D.SKILL_CODE & F.SKILL_CODE
        AND D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "Python") THEN "A"
    WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "C#") THEN "B"
    WHEN D.SKILL_CODE & F.SKILL_CODE THEN "C"
    ELSE NULL END AS GRADE
    , ID, EMAIL
    FROM DEVELOPERS D, FRONT F
)

SELECT GRADE, ID, EMAIL
FROM GRADE_TABLE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID